#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HEIGHT_MAP_WIDTH_SCALE 10.0f
#define HEIGHT_MAP_HEIGHT_SCALE 10.0f

#define DEFUALT_SCREEN_WIDTH 1900
#define DEFUALT_SCREEN_HEIGHT 600

#define OBSERVER_FBO_WIDTH 1024
#define OBSERVER_FBO_HEIGHT 1024

#define DEFUALT_ZOOM 15

#endif // CONSTANTS_H
